"""
Plot Performance Log — Smooth Walk +600mm (WALKING phase only)
==============================================================
Reads the CSV generated by PerformanceLogger in sim_smooth_walk_600.py
and produces two figure windows:

  Figure 1 — Kinematic Accuracy
      Per-leg subplots: X and Z setpoint vs actual (mm) over time.

  Figure 2 — Motor Tracking Performance
      Per-leg subplots: theta1 & theta2 setpoint vs actual (deg) over time.

Each figure also shows the tracking error (setpoint − actual) and prints
summary statistics (RMSE, max absolute error) per leg to the console.

Usage:
    python plot_perf_walk600.py                       # auto-find latest log
    python plot_perf_walk600.py logs/perf_walk600_*.csv  # specify file
"""

import sys
import os
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================================
# LOAD DATA
# ============================================================================

def find_latest_log():
    """Find the most recent perf_walk600_*.csv in the logs/ directory."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    pattern = os.path.join(script_dir, "logs", "perf_walk600_*.csv")
    files = sorted(glob.glob(pattern))
    if not files:
        print("ERROR: No perf_walk600_*.csv found in logs/")
        sys.exit(1)
    return files[-1]


def load_walking_data(csv_path):
    """Load CSV and filter to WALKING phase only."""
    df = pd.read_csv(csv_path)
    df_walk = df[df['phase'] == 'WALKING'].copy()
    if df_walk.empty:
        print("ERROR: No WALKING phase data in the CSV.")
        sys.exit(1)
    # Normalize time to start from 0
    t0 = df_walk['time_s'].iloc[0]
    df_walk['t'] = df_walk['time_s'] - t0
    print(f"  Loaded: {csv_path}")
    print(f"  WALKING phase: {len(df_walk)} rows, "
          f"{df_walk['time_s'].iloc[0]:.2f} – {df_walk['time_s'].iloc[-1]:.2f} s")
    return df_walk


# ============================================================================
# STATISTICS
# ============================================================================

def rmse(err):
    return np.sqrt(np.mean(err ** 2))


def print_stats(df_walk, legs):
    """Print RMSE and max absolute error summary table."""
    print("\n" + "=" * 78)
    print("  WALKING PHASE — PERFORMANCE SUMMARY")
    print("=" * 78)

    # --- Kinematic ---
    print("\n  [Kinematic Accuracy]  (mm)")
    print(f"  {'Leg':>4s}  {'X_rmse':>8s} {'X_max':>8s}  "
          f"{'Z_rmse':>8s} {'Z_max':>8s}")
    print("  " + "-" * 42)
    for leg in legs:
        d = df_walk[df_walk['leg'] == leg]
        ex = d['x_setpoint_mm'] - d['x_actual_mm']
        ez = d['z_setpoint_mm'] - d['z_actual_mm']
        print(f"  {leg:>4s}  {rmse(ex):8.3f} {ex.abs().max():8.3f}  "
              f"{rmse(ez):8.3f} {ez.abs().max():8.3f}")

    # --- Motor ---
    print(f"\n  [Motor Tracking Performance]  (deg)")
    print(f"  {'Leg':>4s}  {'θ1_rmse':>8s} {'θ1_max':>8s}  "
          f"{'θ2_rmse':>8s} {'θ2_max':>8s}")
    print("  " + "-" * 42)
    for leg in legs:
        d = df_walk[df_walk['leg'] == leg]
        e1 = d['theta1_setpoint_deg'] - d['theta1_actual_deg']
        e2 = d['theta2_setpoint_deg'] - d['theta2_actual_deg']
        print(f"  {leg:>4s}  {rmse(e1):8.3f} {e1.abs().max():8.3f}  "
              f"{rmse(e2):8.3f} {e2.abs().max():8.3f}")
    print("=" * 78 + "\n")


# ============================================================================
# FIGURE 1 — KINEMATIC ACCURACY
# ============================================================================

def plot_kinematic_accuracy(df_walk, legs):
    fig, axes = plt.subplots(len(legs), 2, figsize=(14, 10), sharex=True)
    fig.suptitle("Kinematic Accuracy — WALKING Phase\n"
                 "(Foot position in body frame, setpoint vs actual)",
                 fontsize=13, fontweight='bold')

    colors = {'setpoint': '#1f77b4', 'actual': '#ff7f0e', 'error': '#d62728'}

    for i, leg in enumerate(legs):
        d = df_walk[df_walk['leg'] == leg]
        t = d['t'].values

        # --- X axis ---
        ax_x = axes[i, 0]
        ax_x.plot(t, d['x_setpoint_mm'], lw=1.2, color=colors['setpoint'],
                  label='Setpoint')
        ax_x.plot(t, d['x_actual_mm'], lw=1.0, color=colors['actual'],
                  alpha=0.8, label='Actual')
        ax_x_err = ax_x.twinx()
        err_x = (d['x_setpoint_mm'] - d['x_actual_mm']).values
        ax_x_err.fill_between(t, err_x, alpha=0.15, color=colors['error'])
        ax_x_err.plot(t, err_x, lw=0.6, color=colors['error'],
                      alpha=0.5, label='Error')
        ax_x_err.set_ylabel('Error (mm)', fontsize=8, color=colors['error'])
        ax_x_err.tick_params(axis='y', labelsize=7, labelcolor=colors['error'])

        ax_x.set_ylabel(f'{leg}  X (mm)', fontsize=9)
        ax_x.tick_params(axis='y', labelsize=8)
        if i == 0:
            ax_x.legend(loc='upper left', fontsize=7)

        # --- Z axis ---
        ax_z = axes[i, 1]
        ax_z.plot(t, d['z_setpoint_mm'], lw=1.2, color=colors['setpoint'],
                  label='Setpoint')
        ax_z.plot(t, d['z_actual_mm'], lw=1.0, color=colors['actual'],
                  alpha=0.8, label='Actual')
        ax_z_err = ax_z.twinx()
        err_z = (d['z_setpoint_mm'] - d['z_actual_mm']).values
        ax_z_err.fill_between(t, err_z, alpha=0.15, color=colors['error'])
        ax_z_err.plot(t, err_z, lw=0.6, color=colors['error'],
                      alpha=0.5, label='Error')
        ax_z_err.set_ylabel('Error (mm)', fontsize=8, color=colors['error'])
        ax_z_err.tick_params(axis='y', labelsize=7, labelcolor=colors['error'])

        ax_z.set_ylabel(f'{leg}  Z (mm)', fontsize=9)
        ax_z.tick_params(axis='y', labelsize=8)
        if i == 0:
            ax_z.legend(loc='upper left', fontsize=7)

    axes[-1, 0].set_xlabel('Time (s)', fontsize=10)
    axes[-1, 1].set_xlabel('Time (s)', fontsize=10)
    axes[0, 0].set_title('Foot X (forward/backward)', fontsize=10)
    axes[0, 1].set_title('Foot Z (vertical)', fontsize=10)

    fig.tight_layout(rect=[0, 0, 1, 0.94])
    return fig


# ============================================================================
# FIGURE 2 — MOTOR TRACKING PERFORMANCE
# ============================================================================

def plot_motor_tracking(df_walk, legs):
    fig, axes = plt.subplots(len(legs), 2, figsize=(14, 10), sharex=True)
    fig.suptitle("Motor Tracking Performance — WALKING Phase\n"
                 "(Joint angle setpoint vs actual)",
                 fontsize=13, fontweight='bold')

    colors = {'setpoint': '#2ca02c', 'actual': '#9467bd', 'error': '#d62728'}

    for i, leg in enumerate(legs):
        d = df_walk[df_walk['leg'] == leg]
        t = d['t'].values

        # --- Theta 1 (thigh) ---
        ax1 = axes[i, 0]
        ax1.plot(t, d['theta1_setpoint_deg'], lw=1.2, color=colors['setpoint'],
                 label='Setpoint')
        ax1.plot(t, d['theta1_actual_deg'], lw=1.0, color=colors['actual'],
                 alpha=0.8, label='Actual')
        ax1_err = ax1.twinx()
        err1 = (d['theta1_setpoint_deg'] - d['theta1_actual_deg']).values
        ax1_err.fill_between(t, err1, alpha=0.15, color=colors['error'])
        ax1_err.plot(t, err1, lw=0.6, color=colors['error'],
                     alpha=0.5, label='Error')
        ax1_err.set_ylabel('Error (°)', fontsize=8, color=colors['error'])
        ax1_err.tick_params(axis='y', labelsize=7, labelcolor=colors['error'])

        ax1.set_ylabel(f'{leg}  θ1 (°)', fontsize=9)
        ax1.tick_params(axis='y', labelsize=8)
        if i == 0:
            ax1.legend(loc='upper left', fontsize=7)

        # --- Theta 2 (shank) ---
        ax2 = axes[i, 1]
        ax2.plot(t, d['theta2_setpoint_deg'], lw=1.2, color=colors['setpoint'],
                 label='Setpoint')
        ax2.plot(t, d['theta2_actual_deg'], lw=1.0, color=colors['actual'],
                 alpha=0.8, label='Actual')
        ax2_err = ax2.twinx()
        err2 = (d['theta2_setpoint_deg'] - d['theta2_actual_deg']).values
        ax2_err.fill_between(t, err2, alpha=0.15, color=colors['error'])
        ax2_err.plot(t, err2, lw=0.6, color=colors['error'],
                     alpha=0.5, label='Error')
        ax2_err.set_ylabel('Error (°)', fontsize=8, color=colors['error'])
        ax2_err.tick_params(axis='y', labelsize=7, labelcolor=colors['error'])

        ax2.set_ylabel(f'{leg}  θ2 (°)', fontsize=9)
        ax2.tick_params(axis='y', labelsize=8)
        if i == 0:
            ax2.legend(loc='upper left', fontsize=7)

    axes[-1, 0].set_xlabel('Time (s)', fontsize=10)
    axes[-1, 1].set_xlabel('Time (s)', fontsize=10)
    axes[0, 0].set_title('θ1  Thigh Joint', fontsize=10)
    axes[0, 1].set_title('θ2  Shank Joint', fontsize=10)

    fig.tight_layout(rect=[0, 0, 1, 0.94])
    return fig


# ============================================================================
# MAIN
# ============================================================================

def main():
    # Resolve CSV path
    if len(sys.argv) > 1:
        csv_path = sys.argv[1]
    else:
        csv_path = find_latest_log()

    df_walk = load_walking_data(csv_path)
    legs = ['FR', 'FL', 'RR', 'RL']

    print_stats(df_walk, legs)
    plot_kinematic_accuracy(df_walk, legs)
    plot_motor_tracking(df_walk, legs)
    plt.show()


if __name__ == "__main__":
    main()
